const endpoints = {
   processLogin: 'processLogin',
   dashboard: 'dashboard',
   startup: 'startup_api',
   updateDeviceId: 'updateDeviceId',
   getAllOrganization:'getAllOrganization',
   getAllState:'getAllState',
   getAllCity:'getAllCity',
   processRegistration:'processRegistration',
   logout:'logout',
   getLeads:'getLeads',
   createLead:'createLead',
   getOutsiders:'getOutsiders',
   getMasterData:'getMasterData',
   getProjects:'getProjects',
   getPersonalDetails:'getPersonalDetails',
   getWorkOverview:'getWorkOverview',
   getRequirementType:'getRequirementType',
   createProject:'createProject',
   updateLead:'updateLead',
   getNotes:'getNotes',
   addNotes:'addNotes',
   requestOtp:'requestOtp',
   shareClient:'shareClient',
   getShareClientTeam:'getShareClientTeam',
   getLeadUsers:'getLeadUsers',
   getActivities:'getActivities',
   getUpcomingActivities:'getUpcomingActivities',
   viewTeam:'viewTeam',
   addActivity:'addActivity',
   shareLead:'shareLead',
   getMyTeam:'getMyTeam',
   addUpcomingActivity:'addUpcomingActivity',
   updateProjectStatus:'updateProjectStatus',
   createReminder:'createReminder',
   getReminders:'getReminders'
};
export { endpoints }